problem_practice/2403/240327/07-django-form/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.detail, name='detail'),
    # path('new/', views.new, name='new'),
    path('create/', views.create, name='create'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:pk>/update/', views.update, name='update'),
]

problem_practice/2403/240327/07-django-form/articles/models.py
from django.db import models


# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=10)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

problem_practice/2403/240327/07-django-form/articles/forms.py
from django import forms 
from .models import Article

# class ArticleForm(forms.Form):
#     # max_length가 필수 인자가 아니며, textfield가 없음
#     # max_length가 제약 조건은 아님, 그냥 속성 정도, 바꿀 수 있음
#     title = forms.CharField(max_length=10)
#     content = forms.CharField(widget=forms.Textarea)

# model form이 meta를 통해서 알아서 model과 매칭시켜서 만들어줌
class ArticleForm(forms.ModelForm):
    title = forms.CharField(
        label ='제목',
        widget=forms.TextInput(
            attrs = {
                'class' : 'my-title',
                'placeholder' : 'Enter the title'
            }
        )
    )

    class Meta:
        # 어떤 모델과 연동?
        model = Article

        # 그 모델에서 어떤 필드를 쓸지
        # 부분 선택시
        # fields = ('title', 'content')
        # 전체 선택시
        fields = '__all__'
        # 특정 model 제외하는 경우
        # exclude = ('title')

problem_practice/2403/240327/07-django-form/articles/views.py
from django.shortcuts import render, redirect
from .models import Article
from .forms import ArticleForm


# Create your views here.
def index(request):
    articles = Article.objects.all()
    context = {
        'articles': articles,
    }
    return render(request, 'articles/index.html', context)


def detail(request, pk):
    article = Article.objects.get(pk=pk)
    context = {
        'article': article,
    }
    return render(request, 'articles/detail.html', context)


# def new(request):
#     # ArticleForm을 사용
#     form = ArticleForm()
#     context = {
#         'form' : form,
#     }
#     return render(request, 'articles/new.html', context)


# def create(request):
#     # title = request.POST.get('title')
#     # content = request.POST.get('content')
#     # article = Article(title=title, content=content)
#     # article.save()

#     form = ArticleForm(request.POST)
#     # 유효성 검사
#     if form.is_valid():
#         # 저장된 객체를 반환해줌
#         article = form.save()
#         return redirect('articles:detail', article.pk)
    
#     # is_valid가 False이면 에러가 나는 이유를 가져다줌
#     context = {
#         'form' : form,
#     }
#     # 에러 난 경우 입력하던 곳을 다시 보여주면서 에러 메시지를 띄워줌
#     return render(request, 'articles/new.html', context)
#     # return redirect('articles:detail', article.pk)

def create(request):
    form = ArticleForm(request.POST)
    if request.method == 'POST': # POST일 때만 봐야 함
        # 유효성 검사, Create
        if form.is_valid():
            # 저장된 객체를 반환해줌
            article = form.save()
            return redirect('articles:detail', article.pk)
    # if, else 내용 순서를 바꾸면 GET이 아닐 때 모두 유효성 검사를 하게 됨
    else: # GET 일때? X => POST가 아닌 다른 모든 경우, 
        form = ArticleForm()
    
    # POST method라서 들어갔지만 valid가 False인 경우 에러 메시지를 가지고 들여쓰기가 동일한 위치인 context로 옴
    context = {
        'form' : form,
    }
    return render(request, 'articles/create.html', context)


def delete(request, pk):
    article = Article.objects.get(pk=pk)
    article.delete()
    return redirect('articles:index')


def edit(request, pk):
    article = Article.objects.get(pk=pk)
    form = ArticleForm(instance=article)
    context = {
        'article': article,
        'form' : form
    }
    return render(request, 'articles/edit.html', context)


def update(request, pk): 
    # title = request.POST.get('title')
    # content = request.POST.get('content')

    # article.title = title
    # article.content = content
    # article.save()

    article = Article.objects.get(pk=pk)
    # 생성과 수정을 구분해줘야 함 -> instance 키워드로 달라짐 (기존 객체 넣기)
    form = ArticleForm(request.POST, instance=article)
    if form.is_valid():
        form.save()
        return redirect('articles:detail', article.pk)
    
    context = {
        'form' : form,
        'article' : article,
    }
   

    return render(request, 'articles/edit.html', context)


def update(request, pk):
    article = Article.objects.get(pk=pk)
    if request.method == 'POST':
        form = ArticleForm(request.POST, instance=article)
        if form.is_valid():
            form.save()
            return redirect('articles:detail', article.pk)
    else:
        form = ArticleForm(instance=article)
    
    context = {
        'form' : form,
        'article' : article,
    }
    return render(request, 'articles/edit.html', context)

problem_practice/2403/240327/07-django-form/articles/templates/articles/create.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>Create</h1>
  <form action="{% url "articles:create" %}" method="POST">
    {% csrf_token %}
    {% comment %} as_div도 가능 {% endcomment %}
    {{ form.as_p }}
    {% comment %} <div>
      <label for="title">Title: </label>
      <input type="text" name="title" id="title">
    </div>
    <div>
      <label for="content">Content: </label>
      <textarea name="content" id="content"></textarea>
    </div> {% endcomment %}
    <input type="submit">
  </form>
  <hr>
  <a href="{% url "articles:index" %}">[back]</a>
</body>
</html>

problem_practice/2403/240327/07-django-form/articles/templates/articles/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>Detail</h1>
  <h2>{{ article.pk }} 번째 글</h2>
  <hr>
  <p>제목: {{ article.title }}</p>
  <p>내용: {{ article.content }}</p>
  <p>작성일: {{ article.created_at }}</p>
  <p>수정일: {{ article.updated_at }}</p>
  <hr>
  <a href="{% url "articles:edit" article.pk %}">EDIT</a>
  <form action="{% url "articles:delete" article.pk %}" method="POST">
    {% csrf_token %}
    <input type="submit" value="DELETE">
  </form>
  <a href="{% url "articles:index" %}">[back]</a>
</body>
</html>

problem_practice/2403/240327/07-django-form/articles/templates/articles/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>Edit</h1>
  <form action="{% url "articles:update" article.pk %}" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    {% comment %} <div>
      <label for="title">Title: </label>
      <input type="text" name="title" id="title" value="{{ article.title }}">
    </div>
    <div>
      <label for="content">Content: </label>
      <textarea name="content" id="content">{{ article.content }}</textarea>
    </div> {% endcomment %}
    <input type="submit">
  </form>
  <hr>
  <a href="{% url "articles:detail" article.pk %}">[back]</a>
</body>
</html>

problem_practice/2403/240327/07-django-form/articles/templates/articles/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>Articles</h1>
  <a href="{% url "articles:create" %}">CREATE</a>
  <hr>
  {% for article in articles %}
    <p>글 번호: {{ article.pk }}</p>
    <a href="{% url "articles:detail" article.pk %}">
      <p>글 제목: {{ article.title }}</p>
    </a>
    <p>글 내용: {{ article.content }}</p>
    <hr>
  {% endfor %}
</body>
</html>