problem_practice/2403/240314/03-django-urls/articles/urls.py
from django.contrib import admin
from django.urls import path
# 명시적 상대 경로 -> 현재 위치에 있는
from . import views

app_name = 'articles'
# 프로젝트의 urls.py에 연결됨, articles/~로 이어짐
urlpatterns = [
    path('index/', views.index, name='index'),
    path('dinner/', views.dinner, name='dinner'),
    path('search/', views.search, name='search'),
    path('throw/', views.throw, name='throw'),
    path('catch/', views.catch, name='catch'),
    path('greeting/<str:name>/', views.greeting),
    path('articles/<int:num>/', views.detail),
]

problem_practice/2403/240314/03-django-urls/firstpjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('pages/', include('pages.urls')),
]

problem_practice/2403/240314/03-django-urls/pages/urls.py
from django.contrib import admin
from django.urls import path
# 명시적 상대 경로 -> 현재 위치에 있는
from . import views

app_name = 'pages'
# 프로젝트의 urls.py에 연결됨, articles/~로 이어짐
urlpatterns = [
    # path('admin/', admin.site.urls),

]

problem_practice/2403/240314/03-django-urls/articles/models.py
from django.db import models

# Create your models here.

problem_practice/2403/240314/03-django-urls/pages/models.py
from django.db import models

# Create your models here.

problem_practice/2403/240314/03-django-urls/articles/views.py
import random
from django.shortcuts import render


# Create your views here.
def index(request):
    context = {
        'name': 'Alice',
    }
    return render(request, 'articles/index.html', context)


def dinner(request):
    foods = [
        '국밥',
        '국수',
        '카레',
        '탕수육',
    ]
    picked = random.choice(foods)
    context = {
        'foods': foods,
        'picked': picked,
    }
    return render(request, 'articles/dinner.html', context)


def search(request):
    return render(request, 'articles/search.html')


def throw(request):
    return render(request, 'articles/throw.html')


def catch(request):
    message = request.GET.get('message')
    context = {
        'message': message,
    }
    return render(request, 'articles/catch.html', context)


def greeting(request, name):
    context = {
        'name': name,
    }
    return render(request, 'articles/greeting.html', context)


def detail(request, num):
    context = {
        'num': num,
    }
    return render(request, 'articles/detail.html', context)

problem_practice/2403/240314/03-django-urls/pages/views.py
from django.shortcuts import render

# Create your views here.

problem_practice/2403/240314/03-django-urls/articles/templates/articles/catch.html
{% extends "base.html" %}

{% block content %}
  <h1>Catch</h1>
  <h2>{{ message }}를 받았습니다!!!</h2>
{% endblock content %}

problem_practice/2403/240314/03-django-urls/articles/templates/articles/detail.html
{% extends "base.html" %}

{% block content %}
  <h1>Detail</h1>
  <h2>{{ num }}번 게시글 입니다.</h2>
{% endblock content %}

problem_practice/2403/240314/03-django-urls/articles/templates/articles/dinner.html
{% extends "base.html" %}

{% block content %}
  <p>{{ picked }} 메뉴는 {{ picked|length }}글자입니다.</p>
  <h2>메뉴판</h2>
  <ul>
    {% for food in foods %}
      <li>{{ food }}</li>
    {% endfor %}
  </ul>

  {% if foods|length == 0 %}
    <p>메뉴가 소진되었습니다.</p>
  {% else %}
    <p>아직 메뉴가 남았습니다.</p>
  {% endif %}
{% endblock content %}

problem_practice/2403/240314/03-django-urls/articles/templates/articles/greeting.html
{% extends "base.html" %}

{% block content %}
  <h1>{{ name }}님 반갑습니다.</h1>
{% endblock content %}

problem_practice/2403/240314/03-django-urls/articles/templates/articles/index.html
{% extends "base.html" %}

{% block content %}
  <h1>안녕하세요, {{ name }}</h1>
  {% comment %} 두개가 동일한 것 {% endcomment %}
  <a href="{% url "articles:index" %}">dinner</a>
  {% comment %} <a href="/dinner/}">dinner</a> {% endcomment %}

  <a href=" {%url "articles:search"%} ">search</a>
  <a href="{%url "articles:throw"%}">throw</a>
{% endblock content %}

problem_practice/2403/240314/03-django-urls/articles/templates/articles/search.html
{% extends "base.html" %}

{% block content %}
  <form action="https://search.naver.com/search.naver" method="GET">
    <label for="message">검색 : </label>
    <input type="text" id="message" name="query">
    <input type="submit">
  </form>
{% endblock content %}

problem_practice/2403/240314/03-django-urls/articles/templates/articles/throw.html
{% extends "base.html" %}

{% block content %}
  <h1>Throw</h1>
  {% comment %} <form action="http://127.0.0.1:8000/catch/" method="GET"> {% endcomment %}
  <form action="{%url "articles:catch"%}" method="GET">
    <input type="text" name="message">
    <input type="submit">
  </form>
{% endblock content %}

problem_practice/2403/240314/03-django-urls/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    {% block style %}
    {% endblock style %}
  </head>
  <body>
    {% block content %}
    {% endblock content %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>